      SUBROUTINE STRESS(AA)
C     调用ELEMENT子程序计算应力
      COMMON /VAR/ NG, MODEX
      COMMON /EL/ IND,NPAR(10),NUMEG,MTOT,NFIRST,NLAST,ITWO
      COMMON /TAPES/ IELMNT,ILOAD,IIN,IOUT
      DIMENSION AA(1)
      
      REWIND IELMNT
      DO 100 N = 1, NUMEG
          NG = N
          READ(IELMNT) NUMEST, NPAR, (AA(I), I=1, NUMEST)
          CALL ELEMNT
  100 CONTINUE
      
      RETURN
      END